name: Test

on:
  push:
    branches:
      - main
      - 'dev**'
  pull_request:

jobs:
  test:
    name: Test on ruby ${{ matrix.ruby_version }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby_version:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'

    steps:
    - uses: actions/checkout@v4

    - uses: hidakatsuya/action-setup-diff-pdf@v1
      with:
        diff-pdf-version: '0.5'

    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true

    - name: Run Tests
      run: xvfb-run -a bundle exec rake test
